blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    # path('', include('authentication.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import Cart_Add, Cart_Remove, Cart_Detail

app_name='cart'

urlpatterns = [
    path('remove/<product_id>', Cart_Remove, name='CartRemove'),
    path('add/<product_id>', Cart_Add, name='CartAdd'),
    path('', Cart_Detail, name='CartDetail')
]

cupons/urls.py
from django.urls import path
from cupons.views import Cupon_Apply

app_name='cupons'

urlpatterns = [
    path('apply', Cupon_Apply, name='apply')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    # path('', include('authentication.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import Order_Create, Admin_Order_Detail
from orders.views import Order_List_View
# from orders.views import Order_Create_View

app_name='orders'

urlpatterns = [
    path('api/order-list', Order_List_View.as_view()),
    # path('api/order-create', Order_Create_View.as_view()),
    path('create/', Order_Create, name='OrderCreate'),
    path('admin/order/<order_id>', Admin_Order_Detail, name='AdminOrderDetail')
]

shop/urls.py
from django.urls import path
from shop.views import Product_List, Product_Detail
from shop.views import Product_List_View, Product_Detail_View
from shop.views import Product_Category_List_View, Category_List_View, Shop_main
from shop.views import Category_Create_View


app_name='shop'

urlpatterns = [

    path('api/prod-list', Product_List_View.as_view()),
    path('api/prod-detail/<int:id>/', Product_Detail_View.as_view()),
    path('api/prod-category-list', Category_List_View.as_view()),
    path('api/prod-category-list-by/<int:id>/', Product_Category_List_View.as_view()),

    path('api/prod-category-add', Category_Create_View.as_view()),

    path('', Product_List, name='ProductList' ),
    # path('', Shop_main, name='ProductList' ),


    path('<category_slug>/', Product_List, name='ProductListByCategory' ),
    path('<int:id>/<slug:slug>/', Product_Detail, name='ProductDetail' ),

    path('<category_slug>/', Product_List_View.as_view(), name='prod_list'),
    path('<int:id>/<slug:slug>/', Product_Detail_View.as_view(), name='prod_detail'),


]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class Cart_Add_Product_Form(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import Cart_Add_Product_Form
from cupons.forms import Cupon_Aplly_Form



@require_POST
def Cart_Add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = Cart_Add_Product_Form(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])

    return redirect('cart:CartDetail')

def Cart_Remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def Cart_Detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = Cart_Add_Product_Form(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    cupon_apply_form = Cupon_Aplly_Form()
    return render(request, 'cart/detail.html',
                 {'cart': cart, 'cupon_apply_form': cupon_apply_form})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="table-cart" border="1px">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td class="cart-img">
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" class="img-responsive" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="http://localhost:8080/cart/add/{{ product.id }}" method="POST" class="add">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    {% csrf_token %}
                    <input type="submit" value="Обновить"></td>
                </form>
            <td><a href="http://localhost:8080/cart/remove/{{ product.id }}">Удалить</a></td>
            <td class="num">{{ item.price }} грн.</td>
            <td class="num">{{ item.total_price }} грн.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        {% if cart.cupon %}
          <tr class="subtotal">
            <td>Сумма без скидки</td>
            <td colspan="4"></td>
            <td>{{ cart.get_total_price }}</td>
          </tr>
          <tr>
            <td>
              "{{ cart.cupon.code }}" купон на ({{ cart.cupon.discount }} % ниже)
            </td>
            <td colspan="4"></td>
            <td class="num discount">- {{ cart.get_discount|floatformat:"2" }} грн.</td>
          </tr>
        {% endif %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price_after_discount|floatformat:"2" }} грн.</td>
        </tr>
    </tbody>
  </table>
  <p>Применить купон</p>
  <form action="{% url "cupon:apply" %}" method="post" class="add">
    {% csrf_token %}
    {{ cupon_apply_form }}
    <input type="submit" value="Обновить">
  </form>
  <p class="text-right">
    <a href="{% url "shop:ProductList"%}" class="btn btn-light">Продолжить Шопинг</a>
    <a href="{% url "orders:OrderCreate" %}" class="btn">Оформить заказ</a>
  </p>
{% endblock %}