blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    # path('', include('authentication.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from cart.views import Cart_Add, Cart_Remove, Cart_Detail

app_name='cart'

urlpatterns = [
    path('remove/<product_id>', Cart_Remove, name='CartRemove'),
    path('add/<product_id>', Cart_Add, name='CartAdd'),
    path('', Cart_Detail, name='CartDetail')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('cupons/', include('cupons.urls', namespace='cupon')),
    # path('', include('authentication.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop.views import Product_List, Product_Detail
from shop.views import Product_List_View, Product_Detail_View
from shop.views import Product_Category_List_View, Category_List_View, Shop_main
from shop.views import Category_Create_View


app_name='shop'

urlpatterns = [

    path('api/prod-list', Product_List_View.as_view()),
    path('api/prod-detail/<int:id>/', Product_Detail_View.as_view()),
    path('api/prod-category-list', Category_List_View.as_view()),
    path('api/prod-category-list-by/<int:id>/', Product_Category_List_View.as_view()),

    path('api/prod-category-add', Category_Create_View.as_view()),

    path('', Product_List, name='ProductList' ),
    # path('', Shop_main, name='ProductList' ),


    path('<category_slug>/', Product_List, name='ProductListByCategory' ),
    path('<int:id>/<slug:slug>/', Product_Detail, name='ProductDetail' ),

    path('<category_slug>/', Product_List_View.as_view(), name='prod_list'),
    path('<int:id>/<slug:slug>/', Product_Detail_View.as_view(), name='prod_detail'),


]

shop/models.py
from django.db import models
from django.urls import reverse



class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/',blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id, self.slug])

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product
from cart.forms import Cart_Add_Product_Form
from django.template.context_processors import csrf
from rest_framework import generics
from .serializers import Category_Serializer, Category_Create_Serializer
from .serializers import Product_Serializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import permissions


class Product_List_View(generics.ListAPIView):

    queryset = Product.objects.filter(available=True)
    serializer_class = Product_Serializer

class Category_List_View(generics.ListAPIView):

    queryset = Category.objects.all()
    serializer_class = Category_Serializer

class Product_Detail_View(APIView):

    queryset = Product.objects.all()

    def get(self, request, id):
        product = get_object_or_404(Product, id=id, available=True)
        serializer = Product_Serializer(product)
        return Response(serializer.data)

class Product_Category_List_View(APIView):

    queryset = Category.objects.all()

    def get(self, request, id):
        category = get_object_or_404(Category, id=id)
        serializer = Category_Serializer(category)
        return Response(serializer.data)


class Category_Create_View(APIView):

    permission_classes = [permissions.AllowAny]

    def post(self, request):

        Cat = Category_Create_Serializer(data=request.data)

        if Cat.is_valid():

            Cat.save()

            return Response({"status": "Create"})


def Product_List(request, category_slug=None):

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render_to_response('shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    }
                  )


def Product_Detail(request, id, slug):

    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = Cart_Add_Product_Form()
    context = {'product': product, 'cart_product_form': cart_product_form}
    context.update(csrf(request))
    return render_to_response('shop/product/detail.html', context)

def Shop_main(request):
    return render_to_response('Shop-main.html')

shop/templates/shop/product/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  {% csrf_token %}
  <div class="product-detail">
    <div class="col-sm-4">
      <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
    </div>
    <div class="col-sm-8">
    {% csrf_token %}
      <h1>{{ product.name }}</h1>
      <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
      <p class="price">{{ product.price }} грн.</p>
      <form action="http://localhost:8080/cart/add/{{ product.id }}" method="POST" class="add" >
{#      <form action="{% url "cart:CartAdd" product.id %}" method="post">#}
      {% csrf_token %}
          {{ cart_product_form }}
          <input type="submit" value="Добавить в корзину">
      </form>
      <span>
        {{ product.description | linebreaks}}
      </span>
    </div>
  </div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul>
      <li {% if not category %} class="selected" {% endif %}>
        <a href="{% url "shop:ProductList" %}">Все</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
          <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="items row">
      {% for product in products %}
        <div class="item col-sm-4">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          {{ product.price }} грн.
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}